<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace OpenAPIServer\Api;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractTechApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractTechApi
{

    /**
     * @var ContainerInterface|null Slim app container instance
     */
    protected $container;

    /**
     * Route Controller constructor receives container
     *
     * @param ContainerInterface|null $container Slim app container instance
     */
    public function __construct(ContainerInterface $container = null)
    {
        $this->container = $container;
    }


    /**
     * PUT addTech
     * Summary: Add tech
     * Notes: Adds the list of learned technologies to that user.
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function addTech(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $discordid = $args['discordid'];
        $queryParams = $request->getQueryParams();
        $tree = (key_exists('tree', $queryParams)) ? $queryParams['tree'] : null;
        $body = $request->getParsedBody();
        $message = "How about implementing addTech as a PUT method in OpenAPIServer\Api\TechApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getLearned
     * Summary: Get Tech
     * Notes: Give back what you have learned from that technology tree.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getLearned(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $discordid = $args['discordid'];
        $message = "How about implementing getLearned as a GET method in OpenAPIServer\Api\TechApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET seeWhoHasLearntIt
     * Summary: Return members who have known a technology
     * Notes: Returns all clan members who have learned that technology
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function seeWhoHasLearntIt(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $clanid = $args['clanid'];
        $queryParams = $request->getQueryParams();
        $tech = (key_exists('tech', $queryParams)) ? $queryParams['tech'] : null;
        $tree = (key_exists('tree', $queryParams)) ? $queryParams['tree'] : null;
        $message = "How about implementing seeWhoHasLearntIt as a GET method in OpenAPIServer\Api\TechApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
