<?php

/**
 * Stiletto API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.0.1
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace OpenAPIServer\Api;

use Psr\Container\ContainerInterface;
use OpenAPIServer\Api\AbstractClustersApi;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use \Slim\Http\Response as Response;
use PDO;
use OpenAPIServer\BDConnection;
class ClustersApi extends AbstractClustersApi
{

    /**
     * GET getClusters
     * Summary: getClusters
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     */
    public function getClusters(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        try {
            $connection = new BDConnection();
            $dbh = $connection->getCon();
            $stmt = $dbh->prepare('select region, name, clan_limit, crossplay from clusters order by region, name, clan_limit');
            $stmt->execute();
            $results = $stmt->fetchAll(PDO::FETCH_ASSOC);

            $body = $response->getBody();
            $body->rewind();
            $body->write(json_encode($results));
            return $response->withStatus(200);
        } catch (PDOException $e){
            return $response->withStatus(503);
        }
    }
}
