<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * BotConfig
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class BotConfig extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "BotConfig",
  "type" : "object",
  "properties" : {
    "serverdiscordid" : {
      "type" : "string"
    },
    "botLanguaje" : {
      "maxLength" : 2,
      "minLength" : 0,
      "type" : "string",
      "default" : "en"
    },
    "readClanLog" : {
      "type" : "boolean",
      "default" : true
    },
    "automaticKick" : {
      "type" : "boolean",
      "default" : false
    },
    "setNotReadyPVP" : {
      "type" : "boolean",
      "default" : false
    },
    "walkeralarm" : {
      "type" : "boolean",
      "default" : false
    }
  },
  "description" : "Discord Bot Configuration"
}
SCHEMA;
}
