<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * InlineResponse2003
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineResponse2003 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "idtrade" : {
      "type" : "integer",
      "description" : "ID of the trade",
      "example" : 0
    },
    "discordid" : {
      "type" : "string",
      "description" : "Discord ID of the trader owner"
    },
    "type" : {
      "type" : "string",
      "description" : "Supply or Demand"
    },
    "resource" : {
      "type" : "string",
      "description" : "Type of resource",
      "example" : "Aloe"
    },
    "amount" : {
      "type" : "integer",
      "description" : "Amount of the resource",
      "example" : 0
    },
    "quality" : {
      "type" : "integer",
      "description" : "Quality of the resource. Max 100",
      "example" : 0
    },
    "region" : {
      "type" : "string",
      "description" : "EU, NA, SA , ASIA, OCE",
      "example" : "EU"
    },
    "nickname" : {
      "type" : "string",
      "description" : "Nick in the game of the trader owner",
      "example" : "Dm94Dani"
    },
    "discordtag" : {
      "type" : "string",
      "description" : "Discord Tag of the trader owner",
      "example" : "Dm94Dani#6385"
    },
    "price" : {
      "type" : "integer"
    }
  }
}
SCHEMA;
}
