<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * InlineResponse2001
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineResponse2001 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "mapid" : {
      "type" : "integer",
      "description" : "Map ID",
      "example" : 0
    },
    "typemap" : {
      "type" : "string",
      "description" : "Name of the type of map",
      "example" : "canyon"
    },
    "discordid" : {
      "type" : "string",
      "description" : "Map owners discord ID",
      "example" : "0000000000000000000"
    },
    "name" : {
      "type" : "string",
      "description" : "Map name",
      "example" : "Example map"
    },
    "dateofburning" : {
      "type" : "string",
      "description" : "Date of the day the map was burned. aaaa-mm-dd",
      "format" : "date",
      "example" : "2020-10-28"
    },
    "pass" : {
      "type" : "string",
      "description" : "Password that has the map",
      "example" : "124567890pass"
    },
    "allowedit" : {
      "type" : "boolean",
      "description" : "Shows whether the map can be edited with the password or not",
      "example" : false
    }
  }
}
SCHEMA;
}
