<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * InlineResponse202
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineResponse202 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "nickname" : {
      "type" : "string",
      "description" : "Name of the user in the game",
      "example" : "TEST USER"
    },
    "discordtag" : {
      "type" : "string",
      "description" : "Tag of discord",
      "example" : "DEMO#0000"
    },
    "clanid" : {
      "type" : "integer",
      "description" : "Clan ID"
    },
    "clanname" : {
      "type" : "string",
      "description" : "Clan name",
      "example" : "Example Clan"
    },
    "leaderid" : {
      "type" : "string",
      "description" : "Discord ID of the clan leader",
      "example" : "000000000000000000"
    }
  }
}
SCHEMA;
}
