<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * InlineResponse2021
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineResponse2021 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "clanid" : {
      "type" : "integer",
      "description" : "Clan ID"
    },
    "clanname" : {
      "type" : "string",
      "description" : "Clan name",
      "example" : "Example Clan"
    },
    "discordid" : {
      "type" : "string",
      "description" : "Discord server clan ID"
    },
    "leaderid" : {
      "type" : "string",
      "description" : "Discord ID of the clan leader",
      "example" : "000000000000000000"
    },
    "invitelink" : {
      "type" : "string",
      "description" : "Discord server invitation code",
      "example" : "PdXxUWd"
    },
    "recruitment" : {
      "type" : "boolean",
      "description" : "It shows whether the clan is recruiting people or not",
      "example" : false
    },
    "flagcolor" : {
      "type" : "string",
      "description" : "Shows the colour of the clan in hexadecimal",
      "example" : "#e3f218"
    },
    "discordTag" : {
      "type" : "string",
      "description" : "Clan leader s discord tag",
      "example" : "DEMO#0000"
    }
  }
}
SCHEMA;
}
