<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * InlineResponse2024
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineResponse2024 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "leaderid" : {
      "type" : "string",
      "description" : "Discord ID of the clan leader",
      "example" : "000000000000000000"
    },
    "id" : {
      "type" : "integer",
      "description" : "ID of the relationship",
      "example" : 0
    },
    "typed" : {
      "type" : "integer",
      "description" : "Type of relationship. 0 PNA, 1 Ally, 2 Enemy, 20 Waiting for cancel war, 10 Waiting for accept ally, 30 False PNA, 31 False Ally, 32 False War",
      "example" : 0
    },
    "flagcolor" : {
      "type" : "string",
      "description" : "Shows the colour of the clan in hexadecimal",
      "example" : "#e3f218"
    },
    "name" : {
      "type" : "string",
      "description" : "Clan name",
      "example" : "Example Clan"
    },
    "symbol" : {
      "type" : "string"
    }
  }
}
SCHEMA;
}
