<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * InlineResponse2002
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineResponse2002 extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "resourceid" : {
      "type" : "integer",
      "description" : "Resource ID",
      "example" : 0
    },
    "mapid" : {
      "type" : "integer",
      "description" : "Map ID",
      "example" : 0
    },
    "resourcetype" : {
      "type" : "string",
      "description" : "Type of resource",
      "example" : "Aloe"
    },
    "quality" : {
      "type" : "integer",
      "description" : "Quality of the resource",
      "example" : 0
    },
    "x" : {
      "type" : "number",
      "description" : "X-coordinate",
      "example" : 120.25
    },
    "y" : {
      "type" : "number",
      "description" : "Y-coordinate",
      "example" : 100.32
    },
    "token" : {
      "type" : "string",
      "description" : "If the map allows resources to be edited it also returns the editing token for that resource. In order to edit or delete this resource, you must",
      "example" : "oneToken123"
    },
    "typemap" : {
      "type" : "string",
      "description" : "Name of the type of map",
      "example" : "canyon"
    }
  }
}
SCHEMA;
}
