<?php

/**
 * Stiletto API
 * PHP version 7.3
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for [Stiletto Web](https://github.com/dm94/stiletto-web)
 * The version of the OpenAPI document: 2.9.0
 * Contact: dm94official@hotmail.es
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * Walker
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Walker extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "discordid" : {
      "minLength" : 1,
      "type" : "string"
    },
    "walkerid" : {
      "type" : "integer"
    },
    "name" : {
      "minLength" : 1,
      "type" : "string"
    },
    "ownerUser" : {
      "minLength" : 1,
      "type" : "string"
    },
    "lastuser" : {
      "minLength" : 1,
      "type" : "string"
    },
    "datelastuse" : {
      "type" : "string",
      "format" : "date"
    },
    "type" : {
      "type" : "string",
      "example" : "Dinghy"
    },
    "walker_use" : {
      "type" : "string",
      "example" : "PVP",
      "enum" : [ "PVP", "Farming", "Personal" ]
    },
    "isReady" : {
      "type" : "boolean"
    },
    "description" : {
      "maxLength" : 200,
      "type" : "string"
    }
  }
}
SCHEMA;
}
